apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-api-inference-extension.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "gateway-api-inference-extension.name" . }}
spec:
  replicas: {{ .Values.inferenceExtension.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "gateway-api-inference-extension.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway-api-inference-extension.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gateway-api-inference-extension.name" . }}
      containers:
      - name: inference-gateway-ext-proc
        image: {{ .Values.inferenceExtension.image.hub }}:{{ .Values.inferenceExtension.image.tag }}
        imagePullPolicy: {{ .Values.inferenceExtension.image.pullPolicy | default "Always" }}
        args:
        - -poolName
        - {{ .Values.inferencePool.name }}
        - -poolNamespace
        - {{ .Release.Namespace }}
        - -v
        - {{ .Values.inferenceExtension.logLevel | default 3 | quote }}
        - -grpcPort
        - {{ .Values.inferenceExtension.grpcPort | default 9002 | quote }}
        - -grpcHealthPort
        - "9003"
        - -metricsPort
        - {{ .Values.inferenceExtension.metricsPort | default 9090 | quote }}
        ports:
        - name: grpc
          containerPort: {{ .Values.inferenceExtension.grpcPort | default 9002 }}
        - name: grpc-health
          containerPort: 9003
        - name: metrics
          containerPort: {{ .Values.inferenceExtension.metricsPort | default 9090 }}
        livenessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-api-inference-extension.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "gateway-api-inference-extension.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.inferenceExtension.grpcPort | default 9002 }}
      targetPort: {{ .Values.inferenceExtension.grpcPort | default 9002 }}
    - name: http-metrics
      protocol: TCP
      port: {{ .Values.inferenceExtension.metricsPort | default 9090 }}
      targetPort: {{ .Values.inferenceExtension.metricsPort | default 9090 }}
  type: ClusterIP
