
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "gateway.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ include "gatewayClass.name" . }}
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
    - name: llm-gw
      protocol: HTTP
      port: {{ .Values.gateway.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "gatewayClass.name" . }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ include "backend.name" . }}
spec:
  endpoints:
    - fqdn:
        hostname: 'foo.bar.com'
        port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "httpRoute.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ include "gateway.name" . }}
      sectionName: llm-gw
  rules:
  - backendRefs:
      - group: gateway.envoyproxy.io
        kind: Backend
        name: {{ include "backend.name" . }}
    timeouts:
      request: "24h"
      backendRequest: "24h"
