apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "backendTrafficPolicy.name" . }}
  namespace: {{ .Release.namespace }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ include "httpRoute.name" . }}
  circuitBreaker:
    maxConnections: 40000
    maxPendingRequests: 40000
    maxParallelRequests: 40000 
  timeout:
    tcp:
      connectTimeout: 24h